20160527
try to uncompress
start to uncompress for 20160527 to 20160527 of dir /data/salrwais/BPH/Whois/API/
RIPE
/data/salrwais/BPH/Whois/API//RIPE/Data/20160527
nothing for /data/salrwais/BPH/Whois/API//RIPE/Data/20160527
AFRINIC
/data/salrwais/BPH/Whois/API//AFRINIC/Data/20160527
nothing for /data/salrwais/BPH/Whois/API//AFRINIC/Data/20160527
Archive:  /data/salrwais/BPH/Whois/bulkWhois/ARIN/20160527/arin.zip
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/arin_db.xml  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/arin_db.txt  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/legacy.xsl  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/README.txt  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/asn.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/bwi.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/net.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/org.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/poc.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/util/anything.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/util/comment.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/util/foreignElements.rnc  
  inflating: /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp/20160527/arin/schemas/util/phone.rnc  
finish 10000 objects of type asn and name asn
finish 20000 objects of type asn and name asn
finish 10000 objects of type person and name person
finish 20000 objects of type person and name person
finish 30000 objects of type person and name person
finish 40000 objects of type person and name person
finish 50000 objects of type person and name person
finish 60000 objects of type person and name person
finish 70000 objects of type person and name person
finish 80000 objects of type person and name person
finish 90000 objects of type person and name person
finish 100000 objects of type person and name person
finish 110000 objects of type person and name person
finish 120000 objects of type person and name person
finish 130000 objects of type person and name person
finish 140000 objects of type person and name person
finish 150000 objects of type person and name person
finish 160000 objects of type person and name person
finish 170000 objects of type person and name person
finish 180000 objects of type person and name person
finish 190000 objects of type person and name person
finish 200000 objects of type person and name person
finish 210000 objects of type person and name person
finish 220000 objects of type person and name person
finish 230000 objects of type person and name person
finish 240000 objects of type person and name person
finish 250000 objects of type person and name person
finish 260000 objects of type person and name person
finish 270000 objects of type person and name person
finish 280000 objects of type person and name person
finish 290000 objects of type person and name person
finish 300000 objects of type person and name person
finish 310000 objects of type person and name person
finish 320000 objects of type person and name person
finish 330000 objects of type person and name person
finish 340000 objects of type person and name person
finish 350000 objects of type person and name person
finish 360000 objects of type person and name person
finish 370000 objects of type person and name person
finish 380000 objects of type person and name person
finish 390000 objects of type person and name person
finish 400000 objects of type person and name person
finish 410000 objects of type person and name person
finish 420000 objects of type person and name person
finish 430000 objects of type person and name person
finish 440000 objects of type person and name person
finish 450000 objects of type person and name person
finish 460000 objects of type person and name person
finish 470000 objects of type person and name person
finish 480000 objects of type person and name person
finish 490000 objects of type person and name person
finish 500000 objects of type person and name person
finish 510000 objects of type person and name person
finish 520000 objects of type person and name person
finish 530000 objects of type person and name person
finish 540000 objects of type person and name person
finish 550000 objects of type person and name person
finish 560000 objects of type person and name person
finish 570000 objects of type person and name person
finish 580000 objects of type person and name person
finish 590000 objects of type person and name person
finish 600000 objects of type person and name person
finish 610000 objects of type person and name person
finish 620000 objects of type person and name person
finish 630000 objects of type person and name person
finish 640000 objects of type person and name person
finish 10000 objects of type org and name org
finish 20000 objects of type org and name org
finish 30000 objects of type org and name org
finish 40000 objects of type org and name org
finish 50000 objects of type org and name org
finish 60000 objects of type org and name org
finish 70000 objects of type org and name org
finish 80000 objects of type org and name org
finish 90000 objects of type org and name org
finish 100000 objects of type org and name org
finish 110000 objects of type org and name org
finish 120000 objects of type org and name org
finish 130000 objects of type org and name org
finish 140000 objects of type org and name org
finish 150000 objects of type org and name org
finish 160000 objects of type org and name org
finish 170000 objects of type org and name org
finish 180000 objects of type org and name org
finish 190000 objects of type org and name org
finish 200000 objects of type org and name org
finish 210000 objects of type org and name org
finish 220000 objects of type org and name org
finish 230000 objects of type org and name org
finish 240000 objects of type org and name org
finish 250000 objects of type org and name org
finish 260000 objects of type org and name org
finish 270000 objects of type org and name org
finish 280000 objects of type org and name org
finish 290000 objects of type org and name org
finish 300000 objects of type org and name org
finish 310000 objects of type org and name org
finish 320000 objects of type org and name org
finish 330000 objects of type org and name org
finish 340000 objects of type org and name org
finish 350000 objects of type org and name org
finish 360000 objects of type org and name org
finish 370000 objects of type org and name org
finish 380000 objects of type org and name org
finish 390000 objects of type org and name org
finish 400000 objects of type org and name org
finish 410000 objects of type org and name org
finish 420000 objects of type org and name org
finish 430000 objects of type org and name org
finish 440000 objects of type org and name org
finish 450000 objects of type org and name org
finish 460000 objects of type org and name org
finish 470000 objects of type org and name org
finish 480000 objects of type org and name org
finish 490000 objects of type org and name org
finish 500000 objects of type org and name org
finish 510000 objects of type org and name org
finish 520000 objects of type org and name org
finish 530000 objects of type org and name org
finish 540000 objects of type org and name org
finish 550000 objects of type org and name org
finish 560000 objects of type org and name org
finish 570000 objects of type org and name org
finish 580000 objects of type org and name org
finish 590000 objects of type org and name org
finish 600000 objects of type org and name org
finish 610000 objects of type org and name org
finish 620000 objects of type org and name org
finish 630000 objects of type org and name org
finish 640000 objects of type org and name org
finish 650000 objects of type org and name org
finish 660000 objects of type org and name org
finish 670000 objects of type org and name org
finish 680000 objects of type org and name org
finish 690000 objects of type org and name org
finish 700000 objects of type org and name org
finish 710000 objects of type org and name org
finish 720000 objects of type org and name org
finish 730000 objects of type org and name org
finish 740000 objects of type org and name org
finish 750000 objects of type org and name org
finish 760000 objects of type org and name org
finish 770000 objects of type org and name org
finish 780000 objects of type org and name org
finish 790000 objects of type org and name org
finish 800000 objects of type org and name org
finish 810000 objects of type org and name org
finish 820000 objects of type org and name org
finish 830000 objects of type org and name org
finish 840000 objects of type org and name org
finish 850000 objects of type org and name org
finish 860000 objects of type org and name org
finish 870000 objects of type org and name org
finish 880000 objects of type org and name org
finish 890000 objects of type org and name org
finish 900000 objects of type org and name org
finish 910000 objects of type org and name org
finish 920000 objects of type org and name org
finish 930000 objects of type org and name org
finish 940000 objects of type org and name org
finish 950000 objects of type org and name org
finish 960000 objects of type org and name org
finish 970000 objects of type org and name org
finish 980000 objects of type org and name org
finish 990000 objects of type org and name org
finish 1000000 objects of type org and name org
finish 1010000 objects of type org and name org
finish 1020000 objects of type org and name org
finish 1030000 objects of type org and name org
finish 1040000 objects of type org and name org
finish 1050000 objects of type org and name org
finish 1060000 objects of type org and name org
finish 1070000 objects of type org and name org
finish 1080000 objects of type org and name org
finish 1090000 objects of type org and name org
finish 1100000 objects of type org and name org
finish 1110000 objects of type org and name org
finish 1120000 objects of type org and name org
finish 1130000 objects of type org and name org
finish 1140000 objects of type org and name org
finish 1150000 objects of type org and name org
finish 1160000 objects of type org and name org
finish 1170000 objects of type org and name org
finish 1180000 objects of type org and name org
finish 1190000 objects of type org and name org
finish 1200000 objects of type org and name org
finish 1210000 objects of type org and name org
finish 1220000 objects of type org and name org
finish 1230000 objects of type org and name org
finish 1240000 objects of type org and name org
finish 1250000 objects of type org and name org
finish 1260000 objects of type org and name org
finish 1270000 objects of type org and name org
finish 1280000 objects of type org and name org
finish 1290000 objects of type org and name org
finish 1300000 objects of type org and name org
finish 1310000 objects of type org and name org
finish 1320000 objects of type org and name org
finish 1330000 objects of type org and name org
finish 1340000 objects of type org and name org
finish 1350000 objects of type org and name org
finish 1360000 objects of type org and name org
finish 1370000 objects of type org and name org
finish 1380000 objects of type org and name org
finish 1390000 objects of type org and name org
finish 1400000 objects of type org and name org
finish 1410000 objects of type org and name org
finish 1420000 objects of type org and name org
finish 1430000 objects of type org and name org
finish 1440000 objects of type org and name org
finish 1450000 objects of type org and name org
finish 1460000 objects of type org and name org
finish 1470000 objects of type org and name org
finish 1480000 objects of type org and name org
finish 1490000 objects of type org and name org
finish 1500000 objects of type org and name org
finish 1510000 objects of type org and name org
finish 1520000 objects of type org and name org
finish 1530000 objects of type org and name org
finish 1540000 objects of type org and name org
finish 1550000 objects of type org and name org
finish 1560000 objects of type org and name org
finish 1570000 objects of type org and name org
finish 1580000 objects of type org and name org
finish 1590000 objects of type org and name org
finish 1600000 objects of type org and name org
finish 1610000 objects of type org and name org
finish 1620000 objects of type org and name org
finish 1630000 objects of type org and name org
finish 1640000 objects of type org and name org
finish 1650000 objects of type org and name org
finish 1660000 objects of type org and name org
finish 1670000 objects of type org and name org
finish 1680000 objects of type org and name org
finish 1690000 objects of type org and name org
finish 1700000 objects of type org and name org
finish 1710000 objects of type org and name org
finish 1720000 objects of type org and name org
finish 1730000 objects of type org and name org
finish 1740000 objects of type org and name org
finish 1750000 objects of type org and name org
finish 1760000 objects of type org and name org
finish 1770000 objects of type org and name org
finish 1780000 objects of type org and name org
finish 1790000 objects of type org and name org
finish 1800000 objects of type org and name org
finish 1810000 objects of type org and name org
finish 1820000 objects of type org and name org
finish 1830000 objects of type org and name org
finish 1840000 objects of type org and name org
finish 1850000 objects of type org and name org
finish 1860000 objects of type org and name org
finish 1870000 objects of type org and name org
finish 1880000 objects of type org and name org
finish 1890000 objects of type org and name org
finish 1900000 objects of type org and name org
finish 1910000 objects of type org and name org
finish 1920000 objects of type org and name org
finish 1930000 objects of type org and name org
finish 1940000 objects of type org and name org
finish 1950000 objects of type org and name org
finish 1960000 objects of type org and name org
finish 1970000 objects of type org and name org
finish 1980000 objects of type org and name org
finish 1990000 objects of type org and name org
finish 2000000 objects of type org and name org
finish 2010000 objects of type org and name org
finish 2020000 objects of type org and name org
finish 2030000 objects of type org and name org
finish 2040000 objects of type org and name org
finish 2050000 objects of type org and name org
finish 2060000 objects of type org and name org
finish 2070000 objects of type org and name org
finish 2080000 objects of type org and name org
finish 2090000 objects of type org and name org
finish 2100000 objects of type org and name org
finish 2110000 objects of type org and name org
finish 2120000 objects of type org and name org
finish 2130000 objects of type org and name org
finish 2140000 objects of type org and name org
finish 2150000 objects of type org and name org
finish 2160000 objects of type org and name org
finish 2170000 objects of type org and name org
finish 2180000 objects of type org and name org
finish 2190000 objects of type org and name org
finish 2200000 objects of type org and name org
finish 2210000 objects of type org and name org
finish 2220000 objects of type org and name org
finish 2230000 objects of type org and name org
finish 2240000 objects of type org and name org
finish 2250000 objects of type org and name org
finish 2260000 objects of type org and name org
finish 2270000 objects of type org and name org
finish 2280000 objects of type org and name org
finish 2290000 objects of type org and name org
finish 2300000 objects of type org and name org
finish 2310000 objects of type org and name org
finish 2320000 objects of type org and name org
finish 2330000 objects of type org and name org
finish 2340000 objects of type org and name org
finish 2350000 objects of type org and name org
finish 2360000 objects of type org and name org
finish 2370000 objects of type org and name org
finish 2380000 objects of type org and name org
finish 2390000 objects of type org and name org
finish 2400000 objects of type org and name org
finish 2410000 objects of type org and name org
finish 2420000 objects of type org and name org
finish 2430000 objects of type org and name org
finish 2440000 objects of type org and name org
finish 2450000 objects of type org and name org
finish 2460000 objects of type org and name org
finish 2470000 objects of type org and name org
finish 2480000 objects of type org and name org
finish 2490000 objects of type org and name org
finish 2500000 objects of type org and name org
finish 2510000 objects of type org and name org
finish 2520000 objects of type org and name org
finish 2530000 objects of type org and name org
finish 2540000 objects of type org and name org
finish 2550000 objects of type org and name org
finish 2560000 objects of type org and name org
finish 2570000 objects of type org and name org
finish 2580000 objects of type org and name org
finish 2590000 objects of type org and name org
finish 2600000 objects of type org and name org
finish 2610000 objects of type org and name org
finish 2620000 objects of type org and name org
finish 2630000 objects of type org and name org
finish 2640000 objects of type org and name org
finish 2650000 objects of type org and name org
finish 2660000 objects of type org and name org
finish 2670000 objects of type org and name org
finish 2680000 objects of type org and name org
finish 2690000 objects of type org and name org
finish 2700000 objects of type org and name org
finish 2710000 objects of type org and name org
finish 2720000 objects of type org and name org
finish 2730000 objects of type org and name org
finish 2740000 objects of type org and name org
finish 2750000 objects of type org and name org
finish 2760000 objects of type org and name org
finish 2770000 objects of type org and name org
finish 2780000 objects of type org and name org
finish 2790000 objects of type org and name org
finish 2800000 objects of type org and name org
finish 2810000 objects of type org and name org
finish 2820000 objects of type org and name org
finish 2830000 objects of type org and name org
finish 2840000 objects of type org and name org
finish 2850000 objects of type org and name org
finish 2860000 objects of type org and name org
finish 2870000 objects of type org and name org
finish 2880000 objects of type org and name org
finish 2890000 objects of type org and name org
finish 2900000 objects of type org and name org
finish 2910000 objects of type org and name org
finish 2920000 objects of type org and name org
finish 2930000 objects of type org and name org
finish 2940000 objects of type org and name org
finish 2950000 objects of type org and name org
finish 2960000 objects of type org and name org
finish 2970000 objects of type org and name org
finish 2980000 objects of type org and name org
finish 2990000 objects of type org and name org
finish 3000000 objects of type org and name org
finish 3010000 objects of type org and name org
finish 3020000 objects of type org and name org
finish 3030000 objects of type org and name org
finish 3040000 objects of type org and name org
finish 3050000 objects of type org and name org
finish 3060000 objects of type org and name org
finish 3070000 objects of type org and name org
finish 3080000 objects of type org and name org
finish 10000 objects of type inetnum and name inetnum
finish 20000 objects of type inetnum and name inetnum
finish 30000 objects of type inetnum and name inetnum
finish 40000 objects of type inetnum and name inetnum
finish 50000 objects of type inetnum and name inetnum
finish 60000 objects of type inetnum and name inetnum
finish 70000 objects of type inetnum and name inetnum
finish 80000 objects of type inetnum and name inetnum
finish 90000 objects of type inetnum and name inetnum
finish 100000 objects of type inetnum and name inetnum
finish 110000 objects of type inetnum and name inetnum
finish 120000 objects of type inetnum and name inetnum
finish 130000 objects of type inetnum and name inetnum
finish 140000 objects of type inetnum and name inetnum
finish 150000 objects of type inetnum and name inetnum
finish 160000 objects of type inetnum and name inetnum
finish 170000 objects of type inetnum and name inetnum
finish 180000 objects of type inetnum and name inetnum
finish 190000 objects of type inetnum and name inetnum
finish 200000 objects of type inetnum and name inetnum
finish 210000 objects of type inetnum and name inetnum
finish 220000 objects of type inetnum and name inetnum
finish 230000 objects of type inetnum and name inetnum
finish 240000 objects of type inetnum and name inetnum
finish 250000 objects of type inetnum and name inetnum
finish 260000 objects of type inetnum and name inetnum
finish 270000 objects of type inetnum and name inetnum
finish 280000 objects of type inetnum and name inetnum
finish 290000 objects of type inetnum and name inetnum
finish 300000 objects of type inetnum and name inetnum
finish 310000 objects of type inetnum and name inetnum
finish 320000 objects of type inetnum and name inetnum
finish 330000 objects of type inetnum and name inetnum
finish 340000 objects of type inetnum and name inetnum
finish 350000 objects of type inetnum and name inetnum
finish 360000 objects of type inetnum and name inetnum
finish 370000 objects of type inetnum and name inetnum
finish 380000 objects of type inetnum and name inetnum
finish 390000 objects of type inetnum and name inetnum
finish 400000 objects of type inetnum and name inetnum
finish 410000 objects of type inetnum and name inetnum
finish 420000 objects of type inetnum and name inetnum
finish 430000 objects of type inetnum and name inetnum
finish 440000 objects of type inetnum and name inetnum
finish 450000 objects of type inetnum and name inetnum
finish 460000 objects of type inetnum and name inetnum
finish 470000 objects of type inetnum and name inetnum
finish 480000 objects of type inetnum and name inetnum
finish 490000 objects of type inetnum and name inetnum
finish 500000 objects of type inetnum and name inetnum
finish 510000 objects of type inetnum and name inetnum
finish 520000 objects of type inetnum and name inetnum
finish 530000 objects of type inetnum and name inetnum
finish 540000 objects of type inetnum and name inetnum
finish 550000 objects of type inetnum and name inetnum
finish 560000 objects of type inetnum and name inetnum
finish 570000 objects of type inetnum and name inetnum
finish 580000 objects of type inetnum and name inetnum
finish 590000 objects of type inetnum and name inetnum
finish 600000 objects of type inetnum and name inetnum
finish 610000 objects of type inetnum and name inetnum
finish 620000 objects of type inetnum and name inetnum
finish 630000 objects of type inetnum and name inetnum
finish 640000 objects of type inetnum and name inetnum
finish 650000 objects of type inetnum and name inetnum
finish 660000 objects of type inetnum and name inetnum
finish 670000 objects of type inetnum and name inetnum
finish 680000 objects of type inetnum and name inetnum
finish 690000 objects of type inetnum and name inetnum
finish 700000 objects of type inetnum and name inetnum
finish 710000 objects of type inetnum and name inetnum
finish 720000 objects of type inetnum and name inetnum
finish 730000 objects of type inetnum and name inetnum
finish 740000 objects of type inetnum and name inetnum
finish 750000 objects of type inetnum and name inetnum
finish 760000 objects of type inetnum and name inetnum
finish 770000 objects of type inetnum and name inetnum
finish 780000 objects of type inetnum and name inetnum
finish 790000 objects of type inetnum and name inetnum
finish 800000 objects of type inetnum and name inetnum
finish 810000 objects of type inetnum and name inetnum
finish 820000 objects of type inetnum and name inetnum
finish 830000 objects of type inetnum and name inetnum
finish 840000 objects of type inetnum and name inetnum
finish 850000 objects of type inetnum and name inetnum
finish 860000 objects of type inetnum and name inetnum
finish 870000 objects of type inetnum and name inetnum
finish 880000 objects of type inetnum and name inetnum
finish 890000 objects of type inetnum and name inetnum
finish 900000 objects of type inetnum and name inetnum
finish 910000 objects of type inetnum and name inetnum
finish 920000 objects of type inetnum and name inetnum
finish 930000 objects of type inetnum and name inetnum
finish 940000 objects of type inetnum and name inetnum
finish 950000 objects of type inetnum and name inetnum
finish 960000 objects of type inetnum and name inetnum
finish 970000 objects of type inetnum and name inetnum
finish 980000 objects of type inetnum and name inetnum
finish 990000 objects of type inetnum and name inetnum
finish 1000000 objects of type inetnum and name inetnum
finish 1010000 objects of type inetnum and name inetnum
finish 1020000 objects of type inetnum and name inetnum
finish 1030000 objects of type inetnum and name inetnum
finish 1040000 objects of type inetnum and name inetnum
finish 1050000 objects of type inetnum and name inetnum
finish 1060000 objects of type inetnum and name inetnum
finish 1070000 objects of type inetnum and name inetnum
finish 1080000 objects of type inetnum and name inetnum
finish 1090000 objects of type inetnum and name inetnum
finish 1100000 objects of type inetnum and name inetnum
finish 1110000 objects of type inetnum and name inetnum
finish 1120000 objects of type inetnum and name inetnum
finish 1130000 objects of type inetnum and name inetnum
finish 1140000 objects of type inetnum and name inetnum
finish 1150000 objects of type inetnum and name inetnum
finish 1160000 objects of type inetnum and name inetnum
finish 1170000 objects of type inetnum and name inetnum
finish 1180000 objects of type inetnum and name inetnum
finish 1190000 objects of type inetnum and name inetnum
finish 1200000 objects of type inetnum and name inetnum
finish 1210000 objects of type inetnum and name inetnum
finish 1220000 objects of type inetnum and name inetnum
finish 1230000 objects of type inetnum and name inetnum
finish 1240000 objects of type inetnum and name inetnum
finish 1250000 objects of type inetnum and name inetnum
finish 1260000 objects of type inetnum and name inetnum
finish 1270000 objects of type inetnum and name inetnum
finish 1280000 objects of type inetnum and name inetnum
finish 1290000 objects of type inetnum and name inetnum
finish 1300000 objects of type inetnum and name inetnum
finish 1310000 objects of type inetnum and name inetnum
finish 1320000 objects of type inetnum and name inetnum
finish 1330000 objects of type inetnum and name inetnum
finish 1340000 objects of type inetnum and name inetnum
finish 1350000 objects of type inetnum and name inetnum
finish 1360000 objects of type inetnum and name inetnum
finish 1370000 objects of type inetnum and name inetnum
finish 1380000 objects of type inetnum and name inetnum
finish 1390000 objects of type inetnum and name inetnum
finish 1400000 objects of type inetnum and name inetnum
finish 1410000 objects of type inetnum and name inetnum
finish 1420000 objects of type inetnum and name inetnum
finish 1430000 objects of type inetnum and name inetnum
finish 1440000 objects of type inetnum and name inetnum
finish 1450000 objects of type inetnum and name inetnum
finish 1460000 objects of type inetnum and name inetnum
finish 1470000 objects of type inetnum and name inetnum
finish 1480000 objects of type inetnum and name inetnum
finish 1490000 objects of type inetnum and name inetnum
finish 1500000 objects of type inetnum and name inetnum
finish 1510000 objects of type inetnum and name inetnum
finish 1520000 objects of type inetnum and name inetnum
finish 1530000 objects of type inetnum and name inetnum
finish 1540000 objects of type inetnum and name inetnum
finish 1550000 objects of type inetnum and name inetnum
finish 1560000 objects of type inetnum and name inetnum
finish 1570000 objects of type inetnum and name inetnum
finish 1580000 objects of type inetnum and name inetnum
finish 1590000 objects of type inetnum and name inetnum
finish 1600000 objects of type inetnum and name inetnum
finish 1610000 objects of type inetnum and name inetnum
finish 1620000 objects of type inetnum and name inetnum
finish 1630000 objects of type inetnum and name inetnum
finish 1640000 objects of type inetnum and name inetnum
finish 1650000 objects of type inetnum and name inetnum
finish 1660000 objects of type inetnum and name inetnum
finish 1670000 objects of type inetnum and name inetnum
finish 1680000 objects of type inetnum and name inetnum
finish 1690000 objects of type inetnum and name inetnum
finish 1700000 objects of type inetnum and name inetnum
finish 1710000 objects of type inetnum and name inetnum
finish 1720000 objects of type inetnum and name inetnum
finish 1730000 objects of type inetnum and name inetnum
finish 1740000 objects of type inetnum and name inetnum
finish 1750000 objects of type inetnum and name inetnum
finish 1760000 objects of type inetnum and name inetnum
finish 1770000 objects of type inetnum and name inetnum
finish 1780000 objects of type inetnum and name inetnum
finish 1790000 objects of type inetnum and name inetnum
finish 1800000 objects of type inet6num and name inetnum
finish 1810000 objects of type inetnum and name inetnum
finish 1820000 objects of type inetnum and name inetnum
finish 1830000 objects of type inetnum and name inetnum
finish 1840000 objects of type inetnum and name inetnum
finish 1850000 objects of type inetnum and name inetnum
finish 1860000 objects of type inetnum and name inetnum
finish 1870000 objects of type inetnum and name inetnum
finish 1880000 objects of type inetnum and name inetnum
finish 1890000 objects of type inetnum and name inetnum
finish 1900000 objects of type inetnum and name inetnum
finish 1910000 objects of type inetnum and name inetnum
finish 1920000 objects of type inetnum and name inetnum
finish 1930000 objects of type inet6num and name inetnum
finish 1940000 objects of type inetnum and name inetnum
finish 1950000 objects of type inetnum and name inetnum
finish 1960000 objects of type inetnum and name inetnum
finish 1970000 objects of type inetnum and name inetnum
finish 1980000 objects of type inetnum and name inetnum
finish 1990000 objects of type inetnum and name inetnum
finish 2000000 objects of type inetnum and name inetnum
finish 2010000 objects of type inetnum and name inetnum
finish 2020000 objects of type inetnum and name inetnum
finish 2030000 objects of type inetnum and name inetnum
finish 2040000 objects of type inetnum and name inetnum
finish 2050000 objects of type inetnum and name inetnum
finish 2060000 objects of type inetnum and name inetnum
finish 2070000 objects of type inetnum and name inetnum
finish 2080000 objects of type inetnum and name inetnum
finish 2090000 objects of type inetnum and name inetnum
finish 2100000 objects of type inetnum and name inetnum
finish 2110000 objects of type inetnum and name inetnum
finish 2120000 objects of type inetnum and name inetnum
finish 2130000 objects of type inetnum and name inetnum
finish 2140000 objects of type inetnum and name inetnum
finish 2150000 objects of type inetnum and name inetnum
finish 2160000 objects of type inetnum and name inetnum
finish 2170000 objects of type inetnum and name inetnum
finish 2180000 objects of type inetnum and name inetnum
finish 2190000 objects of type inetnum and name inetnum
finish 2200000 objects of type inetnum and name inetnum
finish 2210000 objects of type inetnum and name inetnum
finish 2220000 objects of type inetnum and name inetnum
finish 2230000 objects of type inetnum and name inetnum
finish 2240000 objects of type inetnum and name inetnum
finish 2250000 objects of type inetnum and name inetnum
finish 2260000 objects of type inetnum and name inetnum
finish 2270000 objects of type inetnum and name inetnum
finish 2280000 objects of type inetnum and name inetnum
finish 2290000 objects of type inetnum and name inetnum
finish 2300000 objects of type inetnum and name inetnum
finish 2310000 objects of type inetnum and name inetnum
finish 2320000 objects of type inetnum and name inetnum
finish 2330000 objects of type inetnum and name inetnum
finish 2340000 objects of type inetnum and name inetnum
finish 2350000 objects of type inetnum and name inetnum
finish 2360000 objects of type inetnum and name inetnum
finish 2370000 objects of type inetnum and name inetnum
finish 2380000 objects of type inetnum and name inetnum
finish 2390000 objects of type inetnum and name inetnum
finish 2400000 objects of type inetnum and name inetnum
finish 2410000 objects of type inetnum and name inetnum
finish 2420000 objects of type inetnum and name inetnum
finish 2430000 objects of type inetnum and name inetnum
finish 2440000 objects of type inetnum and name inetnum
finish 2450000 objects of type inetnum and name inetnum
finish 2460000 objects of type inetnum and name inetnum
finish 2470000 objects of type inetnum and name inetnum
finish 2480000 objects of type inetnum and name inetnum
finish 2490000 objects of type inetnum and name inetnum
finish 2500000 objects of type inetnum and name inetnum
finish 2510000 objects of type inetnum and name inetnum
finish 2520000 objects of type inetnum and name inetnum
finish 2530000 objects of type inetnum and name inetnum
finish 2540000 objects of type inetnum and name inetnum
finish 2550000 objects of type inetnum and name inetnum
finish 2560000 objects of type inetnum and name inetnum
finish 2570000 objects of type inetnum and name inetnum
finish 2580000 objects of type inetnum and name inetnum
finish 2590000 objects of type inetnum and name inetnum
finish 2600000 objects of type inetnum and name inetnum
finish 2610000 objects of type inetnum and name inetnum
finish 2620000 objects of type inetnum and name inetnum
finish 2630000 objects of type inetnum and name inetnum
finish 2640000 objects of type inetnum and name inetnum
finish 2650000 objects of type inetnum and name inetnum
finish 2660000 objects of type inetnum and name inetnum
finish 2670000 objects of type inetnum and name inetnum
finish 2680000 objects of type inetnum and name inetnum
finish 2690000 objects of type inetnum and name inetnum
finish 2700000 objects of type inetnum and name inetnum
finish 2710000 objects of type inetnum and name inetnum
finish 2720000 objects of type inetnum and name inetnum
finish 2730000 objects of type inet6num and name inetnum
finish 2740000 objects of type inetnum and name inetnum
finish 2750000 objects of type inetnum and name inetnum
finish 2760000 objects of type inetnum and name inetnum
finish 2770000 objects of type inetnum and name inetnum
finish 2780000 objects of type inet6num and name inetnum
finish 2790000 objects of type inetnum and name inetnum
finish 2800000 objects of type inetnum and name inetnum
finish 2810000 objects of type inetnum and name inetnum
finish 2820000 objects of type inetnum and name inetnum
finish 2830000 objects of type inetnum and name inetnum
finish 2840000 objects of type inetnum and name inetnum
finish 2850000 objects of type inetnum and name inetnum
finish 2860000 objects of type inetnum and name inetnum
finish 2870000 objects of type inetnum and name inetnum
finish 2880000 objects of type inetnum and name inetnum
finish 2890000 objects of type inetnum and name inetnum
finish 2900000 objects of type inet6num and name inetnum
finish 2910000 objects of type inetnum and name inetnum
finish 2920000 objects of type inet6num and name inetnum
finish 2930000 objects of type inet6num and name inetnum
finish 2940000 objects of type inet6num and name inetnum
finish 2950000 objects of type inetnum and name inetnum
finish 2960000 objects of type inetnum and name inetnum
finish 2970000 objects of type inetnum and name inetnum
finish 2980000 objects of type inetnum and name inetnum
finish 2990000 objects of type inetnum and name inetnum
finish 3000000 objects of type inetnum and name inetnum
finish 3010000 objects of type inetnum and name inetnum
retrieve 94423904 lines, get 6775001 objects with timeCost 3253.22
retrieve 0 cidr asn mappings
finish 10000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 20000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 30000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 40000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 50000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 60000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 70000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 80000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 90000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 100000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 110000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 120000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 130000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 140000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 150000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 160000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 170000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 180000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 190000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 200000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 210000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 220000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 230000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 240000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 250000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 260000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 270000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 280000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 290000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 300000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 310000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 320000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 330000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 340000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 350000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 360000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 370000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 380000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 390000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 400000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 410000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 420000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 430000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 440000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 450000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 460000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 470000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 480000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 490000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 500000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 510000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 520000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 530000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 540000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 550000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 560000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 570000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 580000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 590000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 600000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 610000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 620000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 630000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 640000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 650000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 660000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 670000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 680000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 690000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 700000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 710000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 720000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 730000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 740000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 750000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 760000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 770000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 780000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 790000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 800000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 810000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 820000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 830000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 840000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 850000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 860000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 870000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 880000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 890000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 900000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 910000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 920000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 930000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 940000 objects of type inetnum and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 950000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 960000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 970000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 980000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 990000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 1000000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 1010000 objects of type inet6num and name inetnum of apnic for resultFile /data/seclab/BPH/Uniform//20160527/inetnum_apnic
finish 10000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 20000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 30000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 40000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 50000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 60000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 70000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 80000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 90000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 100000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 110000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 120000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 130000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 140000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 150000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 160000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 170000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 180000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 190000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 200000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 210000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 220000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 230000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 240000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 250000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 260000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 270000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 280000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 290000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 300000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 310000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 320000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 330000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 340000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 350000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 360000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 370000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 380000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 390000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 400000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 410000 objects of type person and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 420000 objects of type role and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 430000 objects of type irt and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 440000 objects of type mntner and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 450000 objects of type mntner and name person of apnic for resultFile /data/seclab/BPH/Uniform//20160527/person_apnic
finish 10000 objects of type aut-num and name asn of apnic for resultFile /data/seclab/BPH/Uniform//20160527/asn_apnic
finish person with 454893 objects
finish inetnum with 1012823 objects
finish asn with 10687 objects
time cost is 325.41
/data/salrwais/BPH/Whois/API/RIPE/Data/20160527  or /data/salrwais/BPH/Whois/bulkWhois/RIPE/20160527 doesn't exist
retrieve 0 cidr asn mappings
finish 10000 objects of type inetnum and name inetnum
finish 20000 objects of type inetnum and name inetnum
finish 30000 objects of type inetnum and name inetnum
finish 40000 objects of type inetnum and name inetnum
finish 50000 objects of type inetnum and name inetnum
finish 60000 objects of type inetnum and name inetnum
finish 70000 objects of type inetnum and name inetnum
finish 80000 objects of type inetnum and name inetnum
name person, type person/role, fileperson_role
finish 10000 objects of type person/role and name person
name person, type irt, fileirt
finish person with 16388 objects
time cost is 39.00
/data/seclab/BPH/Xianghang/bulkData/Scripts/format//addAsn2Inetnum.sh
20160527
/data/seclab/BPH/Xianghang/bulkData/Scripts/format//addAsn2Inetnum.py /data/seclab/BPH/Uniform//20160527 /data/salrwais/BPH/Whois/API/BGP//20160527/bpgTable /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp_addAsn2Inetnum_20160527_210317/20160527 ripe
finish retrieving bgp file and get 624104 cidr-asn mappings and failed 0
/data/seclab/BPH/Xianghang/bulkData/Scripts/format//addAsn2Inetnum.py /data/seclab/BPH/Uniform//20160527 /data/salrwais/BPH/Whois/API/BGP//20160527/bpgTable /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp_addAsn2Inetnum_20160527_210317/20160527 apnic
finish retrieving bgp file and get 624104 cidr-asn mappings and failed 0
start to process file:/data/seclab/BPH/Uniform//20160527/inetnum_apnic
add asn to 1000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 2000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 3000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 4000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 5000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 6000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 7000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 8000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 9000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 10000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 11000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 12000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 13000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 14000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 15000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 16000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 17000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 18000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 19000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 20000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 21000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 22000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 23000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 24000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 25000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 26000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 27000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 28000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 29000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 30000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 31000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 32000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 33000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 34000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 35000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 36000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 37000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 38000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 39000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 40000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 41000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 42000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 43000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 44000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 45000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 46000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 47000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 48000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 49000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 50000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 51000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 52000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 53000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 54000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 55000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 56000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 57000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 58000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 59000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 60000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 61000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 62000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 63000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 64000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 65000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 66000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 67000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 68000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 69000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 70000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 71000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 72000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 73000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 74000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 75000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 76000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 77000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 78000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 79000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 80000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 81000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 82000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 83000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 84000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 85000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 86000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 87000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 88000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 89000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 90000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 91000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 92000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 93000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 94000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 95000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 96000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 97000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 98000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 99000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 100000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 101000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 102000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 103000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 104000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 105000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 106000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 107000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 108000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 109000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 110000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 111000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 112000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 113000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 114000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 115000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 116000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 117000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 118000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 119000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 120000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 121000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 122000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 123000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 124000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 125000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 126000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 127000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 128000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 129000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 130000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 131000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 132000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 133000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 134000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 135000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 136000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 137000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 138000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 139000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 140000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 141000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 142000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 143000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 144000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 145000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 146000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 147000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 148000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 149000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 150000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 151000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 152000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 153000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 154000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 155000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 156000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 157000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 158000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 159000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 160000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 161000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 162000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 163000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 164000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 165000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 166000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 167000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 168000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 169000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 170000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 171000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 172000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 173000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 174000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 175000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 176000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 177000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 178000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 179000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 180000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 181000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 182000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 183000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 184000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 185000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 186000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 187000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 188000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 189000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 190000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 191000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 192000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 193000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 194000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 195000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 196000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 197000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 198000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 199000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 200000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 201000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 202000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 203000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 204000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 205000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 206000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 207000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 208000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 209000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 210000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 211000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 212000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 213000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 214000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 215000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 216000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 217000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 218000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 219000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 220000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 221000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 222000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 223000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 224000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 225000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 226000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 227000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 228000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 229000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 230000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 231000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 232000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 233000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 234000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 235000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 236000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 237000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 238000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 239000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 240000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 241000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 242000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 243000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 244000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 245000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 246000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 247000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 248000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 249000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 250000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 251000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 252000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 253000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 254000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 255000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 256000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 257000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 258000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 259000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 260000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 261000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 262000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 263000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 264000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 265000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 266000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 267000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 268000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 269000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 270000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 271000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 272000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 273000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 274000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 275000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 276000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 277000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 278000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 279000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 280000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 281000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 282000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 283000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 284000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 285000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 286000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 287000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 288000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 289000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 290000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 291000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 292000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 293000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 294000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 295000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 296000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 297000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 298000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 299000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 300000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 301000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 302000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 303000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 304000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 305000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 306000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 307000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 308000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 309000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 310000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 311000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 312000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 313000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 314000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 315000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 316000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 317000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 318000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 319000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 320000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 321000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 322000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 323000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 324000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 325000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 326000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 327000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 328000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 329000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 330000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 331000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 332000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 333000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 334000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 335000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 336000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 337000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 338000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 339000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 340000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 341000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 342000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 343000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 344000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 345000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 346000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 347000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 348000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 349000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 350000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 351000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 352000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 353000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 354000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 355000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 356000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 357000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 358000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 359000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 360000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 361000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 362000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 363000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 364000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 365000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 366000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 367000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 368000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 369000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 370000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 371000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 372000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 373000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 374000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 375000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 376000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 377000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 378000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 379000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 380000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 381000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 382000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 383000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 384000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 385000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 386000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 387000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 388000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 389000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 390000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 391000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 392000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 393000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 394000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 395000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 396000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 397000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 398000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 399000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 400000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 401000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 402000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 403000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 404000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 405000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 406000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 407000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 408000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 409000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 410000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 411000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 412000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 413000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 414000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 415000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 416000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 417000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 418000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 419000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 420000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 421000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 422000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 423000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 424000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 425000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 426000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 427000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 428000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 429000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 430000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 431000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 432000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 433000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 434000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 435000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 436000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 437000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 438000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 439000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 440000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 441000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 442000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 443000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 444000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 445000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 446000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 447000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 448000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 449000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 450000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 451000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 452000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 453000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 454000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 455000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 456000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 457000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 458000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 459000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 460000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 461000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 462000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 463000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 464000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 465000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 466000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 467000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 468000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 469000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 470000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 471000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 472000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 473000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 474000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 475000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 476000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 477000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 478000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 479000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 480000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 481000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 482000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 483000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 484000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 485000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 486000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 487000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 488000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 489000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 490000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 491000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 492000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 493000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 494000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 495000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 496000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 497000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 498000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 499000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 500000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 501000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 502000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 503000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 504000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 505000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 506000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 507000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 508000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 509000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 510000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 511000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 512000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 513000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 514000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 515000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 516000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 517000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 518000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 519000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 520000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 521000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 522000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 523000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 524000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 525000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 526000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 527000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 528000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 529000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 530000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 531000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 532000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 533000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 534000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 535000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 536000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 537000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 538000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 539000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 540000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 541000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 542000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 543000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 544000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 545000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 546000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 547000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 548000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 549000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 550000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 551000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 552000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 553000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 554000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 555000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 556000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 557000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 558000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 559000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 560000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 561000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 562000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 563000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 564000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 565000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 566000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 567000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 568000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 569000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 570000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 571000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 572000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 573000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 574000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 575000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 576000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 577000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 578000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 579000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 580000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 581000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 582000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 583000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 584000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 585000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 586000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 587000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 588000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 589000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 590000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 591000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 592000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 593000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 594000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 595000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 596000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 597000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 598000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 599000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 600000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 601000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 602000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 603000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 604000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 605000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 606000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 607000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 608000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 609000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 610000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 611000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 612000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 613000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 614000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 615000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 616000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 617000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 618000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 619000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 620000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 621000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 622000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 623000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 624000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 625000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 626000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 627000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 628000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 629000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 630000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 631000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 632000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 633000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 634000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 635000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 636000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 637000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 638000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 639000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 640000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 641000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 642000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 643000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 644000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 645000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 646000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 647000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 648000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 649000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 650000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 651000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 652000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 653000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 654000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 655000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 656000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 657000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 658000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 659000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 660000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 661000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 662000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 663000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 664000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 665000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 666000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 667000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 668000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 669000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 670000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 671000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 672000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 673000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 674000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 675000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 676000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 677000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 678000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 679000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 680000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 681000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 682000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 683000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 684000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 685000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 686000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 687000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 688000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 689000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 690000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 691000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 692000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 693000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 694000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 695000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 696000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 697000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 698000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 699000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 700000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 701000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 702000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 703000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 704000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 705000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 706000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 707000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 708000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 709000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 710000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 711000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 712000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 713000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 714000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 715000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 716000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 717000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 718000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 719000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 720000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 721000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 722000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 723000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 724000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 725000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 726000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 727000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 728000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 729000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 730000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 731000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 732000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 733000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 734000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 735000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 736000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 737000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 738000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 739000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 740000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 741000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 742000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 743000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 744000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 745000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 746000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 747000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 748000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 749000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 750000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 751000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 752000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 753000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 754000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 755000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 756000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 757000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 758000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 759000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 760000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 761000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 762000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 763000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 764000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 765000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 766000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 767000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 768000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 769000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 770000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 771000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 772000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 773000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 774000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 775000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 776000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 777000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 778000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 779000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 780000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 781000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 782000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 783000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 784000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 785000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 786000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 787000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 788000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 789000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 790000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 791000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 792000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 793000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 794000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 795000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 796000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 797000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 798000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 799000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 800000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 801000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 802000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 803000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 804000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 805000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 806000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 807000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 808000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 809000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 810000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 811000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 812000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 813000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 814000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 815000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 816000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 817000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 818000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 819000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 820000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 821000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 822000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 823000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 824000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 825000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 826000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 827000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 828000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 829000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 830000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 831000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 832000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 833000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 834000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 835000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 836000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 837000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 838000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 839000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 840000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 841000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 842000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 843000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 844000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 845000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 846000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 847000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 848000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 849000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 850000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 851000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 852000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 853000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 854000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 855000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 856000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 857000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 858000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 859000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 860000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 861000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 862000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 863000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 864000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 865000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 866000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 867000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 868000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 869000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 870000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 871000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 872000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 873000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 874000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 875000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 876000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 877000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 878000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 879000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 880000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 881000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 882000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 883000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 884000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 885000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 886000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 887000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 888000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 889000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 890000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 891000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 892000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 893000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 894000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 895000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 896000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 897000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 898000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 899000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 900000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 901000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 902000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 903000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 904000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 905000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 906000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 907000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 908000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 909000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 910000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 911000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 912000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 913000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 914000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 915000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 916000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 917000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 918000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 919000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 920000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 921000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 922000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 923000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 924000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 925000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 926000 inetnums from registry apnic, among them, 0 are ipv6
add asn to 927000 inetnums from registry apnic, among them, 856 are ipv6
add asn to 928000 inetnums from registry apnic, among them, 1856 are ipv6
add asn to 929000 inetnums from registry apnic, among them, 2856 are ipv6
add asn to 930000 inetnums from registry apnic, among them, 3856 are ipv6
add asn to 931000 inetnums from registry apnic, among them, 4856 are ipv6
add asn to 932000 inetnums from registry apnic, among them, 5856 are ipv6
add asn to 933000 inetnums from registry apnic, among them, 6856 are ipv6
add asn to 934000 inetnums from registry apnic, among them, 7856 are ipv6
add asn to 935000 inetnums from registry apnic, among them, 8856 are ipv6
add asn to 936000 inetnums from registry apnic, among them, 9856 are ipv6
add asn to 937000 inetnums from registry apnic, among them, 10856 are ipv6
add asn to 938000 inetnums from registry apnic, among them, 11856 are ipv6
add asn to 939000 inetnums from registry apnic, among them, 12856 are ipv6
add asn to 940000 inetnums from registry apnic, among them, 13856 are ipv6
add asn to 941000 inetnums from registry apnic, among them, 14856 are ipv6
add asn to 942000 inetnums from registry apnic, among them, 15856 are ipv6
add asn to 943000 inetnums from registry apnic, among them, 16856 are ipv6
add asn to 944000 inetnums from registry apnic, among them, 17856 are ipv6
add asn to 945000 inetnums from registry apnic, among them, 18856 are ipv6
add asn to 946000 inetnums from registry apnic, among them, 19856 are ipv6
add asn to 947000 inetnums from registry apnic, among them, 20856 are ipv6
add asn to 948000 inetnums from registry apnic, among them, 21856 are ipv6
add asn to 949000 inetnums from registry apnic, among them, 22856 are ipv6
add asn to 950000 inetnums from registry apnic, among them, 23856 are ipv6
add asn to 951000 inetnums from registry apnic, among them, 24856 are ipv6
add asn to 952000 inetnums from registry apnic, among them, 25856 are ipv6
add asn to 953000 inetnums from registry apnic, among them, 26856 are ipv6
add asn to 954000 inetnums from registry apnic, among them, 27856 are ipv6
add asn to 955000 inetnums from registry apnic, among them, 28856 are ipv6
add asn to 956000 inetnums from registry apnic, among them, 29856 are ipv6
add asn to 957000 inetnums from registry apnic, among them, 30856 are ipv6
add asn to 958000 inetnums from registry apnic, among them, 31856 are ipv6
add asn to 959000 inetnums from registry apnic, among them, 32856 are ipv6
add asn to 960000 inetnums from registry apnic, among them, 33856 are ipv6
add asn to 961000 inetnums from registry apnic, among them, 34856 are ipv6
add asn to 962000 inetnums from registry apnic, among them, 35856 are ipv6
add asn to 963000 inetnums from registry apnic, among them, 36856 are ipv6
add asn to 964000 inetnums from registry apnic, among them, 37856 are ipv6
add asn to 965000 inetnums from registry apnic, among them, 38856 are ipv6
add asn to 966000 inetnums from registry apnic, among them, 39856 are ipv6
add asn to 967000 inetnums from registry apnic, among them, 40856 are ipv6
add asn to 968000 inetnums from registry apnic, among them, 41856 are ipv6
add asn to 969000 inetnums from registry apnic, among them, 42856 are ipv6
add asn to 970000 inetnums from registry apnic, among them, 43856 are ipv6
add asn to 971000 inetnums from registry apnic, among them, 44856 are ipv6
add asn to 972000 inetnums from registry apnic, among them, 45856 are ipv6
add asn to 973000 inetnums from registry apnic, among them, 46856 are ipv6
add asn to 974000 inetnums from registry apnic, among them, 47856 are ipv6
add asn to 975000 inetnums from registry apnic, among them, 48856 are ipv6
add asn to 976000 inetnums from registry apnic, among them, 49856 are ipv6
add asn to 977000 inetnums from registry apnic, among them, 50856 are ipv6
add asn to 978000 inetnums from registry apnic, among them, 51856 are ipv6
add asn to 979000 inetnums from registry apnic, among them, 52856 are ipv6
add asn to 980000 inetnums from registry apnic, among them, 53856 are ipv6
add asn to 981000 inetnums from registry apnic, among them, 54856 are ipv6
add asn to 982000 inetnums from registry apnic, among them, 55856 are ipv6
add asn to 983000 inetnums from registry apnic, among them, 56856 are ipv6
add asn to 984000 inetnums from registry apnic, among them, 57856 are ipv6
add asn to 985000 inetnums from registry apnic, among them, 58856 are ipv6
add asn to 986000 inetnums from registry apnic, among them, 59856 are ipv6
complement asn for 986344 (60200 are ipv6) out of 1012824 inetnum objects from apnic registry
/data/seclab/BPH/Xianghang/bulkData/Scripts/format//addAsn2Inetnum.py /data/seclab/BPH/Uniform//20160527 /data/salrwais/BPH/Whois/API/BGP//20160527/bpgTable /data/seclab/BPH/Xianghang/bulkData/Scripts/format//temp_addAsn2Inetnum_20160527_210317/20160527 arin
finish retrieving bgp file and get 624104 cidr-asn mappings and failed 0
start to process file:/data/seclab/BPH/Uniform//20160527/inetnum_arin
add asn to 1000 inetnums from registry arin, among them, 0 are ipv6
add asn to 2000 inetnums from registry arin, among them, 0 are ipv6
add asn to 3000 inetnums from registry arin, among them, 0 are ipv6
add asn to 4000 inetnums from registry arin, among them, 0 are ipv6
add asn to 5000 inetnums from registry arin, among them, 0 are ipv6
add asn to 6000 inetnums from registry arin, among them, 0 are ipv6
add asn to 7000 inetnums from registry arin, among them, 0 are ipv6
add asn to 8000 inetnums from registry arin, among them, 0 are ipv6
add asn to 9000 inetnums from registry arin, among them, 0 are ipv6
add asn to 10000 inetnums from registry arin, among them, 0 are ipv6
add asn to 11000 inetnums from registry arin, among them, 0 are ipv6
add asn to 12000 inetnums from registry arin, among them, 0 are ipv6
add asn to 13000 inetnums from registry arin, among them, 0 are ipv6
add asn to 14000 inetnums from registry arin, among them, 0 are ipv6
add asn to 15000 inetnums from registry arin, among them, 0 are ipv6
add asn to 16000 inetnums from registry arin, among them, 0 are ipv6
add asn to 17000 inetnums from registry arin, among them, 0 are ipv6
add asn to 18000 inetnums from registry arin, among them, 0 are ipv6
add asn to 19000 inetnums from registry arin, among them, 0 are ipv6
add asn to 20000 inetnums from registry arin, among them, 0 are ipv6
add asn to 21000 inetnums from registry arin, among them, 0 are ipv6
add asn to 22000 inetnums from registry arin, among them, 0 are ipv6
add asn to 23000 inetnums from registry arin, among them, 0 are ipv6
add asn to 24000 inetnums from registry arin, among them, 0 are ipv6
add asn to 25000 inetnums from registry arin, among them, 0 are ipv6
add asn to 26000 inetnums from registry arin, among them, 0 are ipv6
add asn to 27000 inetnums from registry arin, among them, 0 are ipv6
add asn to 28000 inetnums from registry arin, among them, 0 are ipv6
add asn to 29000 inetnums from registry arin, among them, 0 are ipv6
add asn to 30000 inetnums from registry arin, among them, 0 are ipv6
add asn to 31000 inetnums from registry arin, among them, 0 are ipv6
add asn to 32000 inetnums from registry arin, among them, 0 are ipv6
add asn to 33000 inetnums from registry arin, among them, 0 are ipv6
add asn to 34000 inetnums from registry arin, among them, 0 are ipv6
add asn to 35000 inetnums from registry arin, among them, 0 are ipv6
add asn to 36000 inetnums from registry arin, among them, 0 are ipv6
add asn to 37000 inetnums from registry arin, among them, 0 are ipv6
add asn to 38000 inetnums from registry arin, among them, 0 are ipv6
add asn to 39000 inetnums from registry arin, among them, 0 are ipv6
add asn to 40000 inetnums from registry arin, among them, 0 are ipv6
add asn to 41000 inetnums from registry arin, among them, 0 are ipv6
add asn to 42000 inetnums from registry arin, among them, 0 are ipv6
add asn to 43000 inetnums from registry arin, among them, 0 are ipv6
add asn to 44000 inetnums from registry arin, among them, 0 are ipv6
add asn to 45000 inetnums from registry arin, among them, 0 are ipv6
add asn to 46000 inetnums from registry arin, among them, 0 are ipv6
add asn to 47000 inetnums from registry arin, among them, 0 are ipv6
add asn to 48000 inetnums from registry arin, among them, 0 are ipv6
add asn to 49000 inetnums from registry arin, among them, 0 are ipv6
add asn to 50000 inetnums from registry arin, among them, 0 are ipv6
add asn to 51000 inetnums from registry arin, among them, 0 are ipv6
add asn to 52000 inetnums from registry arin, among them, 0 are ipv6
add asn to 53000 inetnums from registry arin, among them, 0 are ipv6
add asn to 54000 inetnums from registry arin, among them, 0 are ipv6
add asn to 55000 inetnums from registry arin, among them, 0 are ipv6
add asn to 56000 inetnums from registry arin, among them, 0 are ipv6
add asn to 57000 inetnums from registry arin, among them, 0 are ipv6
add asn to 58000 inetnums from registry arin, among them, 0 are ipv6
add asn to 59000 inetnums from registry arin, among them, 0 are ipv6
add asn to 60000 inetnums from registry arin, among them, 0 are ipv6
add asn to 61000 inetnums from registry arin, among them, 0 are ipv6
add asn to 62000 inetnums from registry arin, among them, 0 are ipv6
add asn to 63000 inetnums from registry arin, among them, 0 are ipv6
add asn to 64000 inetnums from registry arin, among them, 0 are ipv6
add asn to 65000 inetnums from registry arin, among them, 0 are ipv6
add asn to 66000 inetnums from registry arin, among them, 0 are ipv6
add asn to 67000 inetnums from registry arin, among them, 0 are ipv6
add asn to 68000 inetnums from registry arin, among them, 0 are ipv6
add asn to 69000 inetnums from registry arin, among them, 0 are ipv6
add asn to 70000 inetnums from registry arin, among them, 0 are ipv6
add asn to 71000 inetnums from registry arin, among them, 0 are ipv6
add asn to 72000 inetnums from registry arin, among them, 0 are ipv6
add asn to 73000 inetnums from registry arin, among them, 0 are ipv6
add asn to 74000 inetnums from registry arin, among them, 0 are ipv6
add asn to 75000 inetnums from registry arin, among them, 0 are ipv6
add asn to 76000 inetnums from registry arin, among them, 0 are ipv6
add asn to 77000 inetnums from registry arin, among them, 0 are ipv6
add asn to 78000 inetnums from registry arin, among them, 0 are ipv6
add asn to 79000 inetnums from registry arin, among them, 0 are ipv6
add asn to 80000 inetnums from registry arin, among them, 0 are ipv6
add asn to 81000 inetnums from registry arin, among them, 0 are ipv6
add asn to 82000 inetnums from registry arin, among them, 0 are ipv6
add asn to 83000 inetnums from registry arin, among them, 0 are ipv6
add asn to 84000 inetnums from registry arin, among them, 0 are ipv6
add asn to 85000 inetnums from registry arin, among them, 0 are ipv6
add asn to 86000 inetnums from registry arin, among them, 0 are ipv6
add asn to 87000 inetnums from registry arin, among them, 0 are ipv6
add asn to 88000 inetnums from registry arin, among them, 0 are ipv6
add asn to 89000 inetnums from registry arin, among them, 0 are ipv6
add asn to 90000 inetnums from registry arin, among them, 0 are ipv6
add asn to 91000 inetnums from registry arin, among them, 0 are ipv6
add asn to 92000 inetnums from registry arin, among them, 0 are ipv6
add asn to 93000 inetnums from registry arin, among them, 0 are ipv6
add asn to 94000 inetnums from registry arin, among them, 0 are ipv6
add asn to 95000 inetnums from registry arin, among them, 0 are ipv6
add asn to 96000 inetnums from registry arin, among them, 0 are ipv6
add asn to 97000 inetnums from registry arin, among them, 0 are ipv6
add asn to 98000 inetnums from registry arin, among them, 0 are ipv6
add asn to 99000 inetnums from registry arin, among them, 0 are ipv6
add asn to 100000 inetnums from registry arin, among them, 0 are ipv6
add asn to 101000 inetnums from registry arin, among them, 0 are ipv6
add asn to 102000 inetnums from registry arin, among them, 0 are ipv6
add asn to 103000 inetnums from registry arin, among them, 0 are ipv6
add asn to 104000 inetnums from registry arin, among them, 0 are ipv6
add asn to 105000 inetnums from registry arin, among them, 0 are ipv6
add asn to 106000 inetnums from registry arin, among them, 0 are ipv6
add asn to 107000 inetnums from registry arin, among them, 0 are ipv6
add asn to 108000 inetnums from registry arin, among them, 0 are ipv6
add asn to 109000 inetnums from registry arin, among them, 0 are ipv6
add asn to 110000 inetnums from registry arin, among them, 0 are ipv6
add asn to 111000 inetnums from registry arin, among them, 0 are ipv6
add asn to 112000 inetnums from registry arin, among them, 0 are ipv6
add asn to 113000 inetnums from registry arin, among them, 0 are ipv6
add asn to 114000 inetnums from registry arin, among them, 0 are ipv6
add asn to 115000 inetnums from registry arin, among them, 0 are ipv6
add asn to 116000 inetnums from registry arin, among them, 0 are ipv6
add asn to 117000 inetnums from registry arin, among them, 0 are ipv6
add asn to 118000 inetnums from registry arin, among them, 0 are ipv6
add asn to 119000 inetnums from registry arin, among them, 0 are ipv6
add asn to 120000 inetnums from registry arin, among them, 0 are ipv6
add asn to 121000 inetnums from registry arin, among them, 0 are ipv6
add asn to 122000 inetnums from registry arin, among them, 0 are ipv6
add asn to 123000 inetnums from registry arin, among them, 0 are ipv6
add asn to 124000 inetnums from registry arin, among them, 0 are ipv6
add asn to 125000 inetnums from registry arin, among them, 0 are ipv6
add asn to 126000 inetnums from registry arin, among them, 0 are ipv6
add asn to 127000 inetnums from registry arin, among them, 0 are ipv6
add asn to 128000 inetnums from registry arin, among them, 0 are ipv6
add asn to 129000 inetnums from registry arin, among them, 0 are ipv6
add asn to 130000 inetnums from registry arin, among them, 0 are ipv6
add asn to 131000 inetnums from registry arin, among them, 0 are ipv6
add asn to 132000 inetnums from registry arin, among them, 0 are ipv6
add asn to 133000 inetnums from registry arin, among them, 0 are ipv6
add asn to 134000 inetnums from registry arin, among them, 0 are ipv6
add asn to 135000 inetnums from registry arin, among them, 0 are ipv6
add asn to 136000 inetnums from registry arin, among them, 0 are ipv6
add asn to 137000 inetnums from registry arin, among them, 0 are ipv6
add asn to 138000 inetnums from registry arin, among them, 0 are ipv6
add asn to 139000 inetnums from registry arin, among them, 0 are ipv6
add asn to 140000 inetnums from registry arin, among them, 0 are ipv6
add asn to 141000 inetnums from registry arin, among them, 0 are ipv6
add asn to 142000 inetnums from registry arin, among them, 0 are ipv6
add asn to 143000 inetnums from registry arin, among them, 0 are ipv6
add asn to 144000 inetnums from registry arin, among them, 0 are ipv6
add asn to 145000 inetnums from registry arin, among them, 0 are ipv6
add asn to 146000 inetnums from registry arin, among them, 0 are ipv6
add asn to 147000 inetnums from registry arin, among them, 0 are ipv6
add asn to 148000 inetnums from registry arin, among them, 0 are ipv6
add asn to 149000 inetnums from registry arin, among them, 0 are ipv6
add asn to 150000 inetnums from registry arin, among them, 0 are ipv6
add asn to 151000 inetnums from registry arin, among them, 0 are ipv6
add asn to 152000 inetnums from registry arin, among them, 0 are ipv6
add asn to 153000 inetnums from registry arin, among them, 0 are ipv6
add asn to 154000 inetnums from registry arin, among them, 0 are ipv6
add asn to 155000 inetnums from registry arin, among them, 0 are ipv6
add asn to 156000 inetnums from registry arin, among them, 0 are ipv6
add asn to 157000 inetnums from registry arin, among them, 0 are ipv6
add asn to 158000 inetnums from registry arin, among them, 0 are ipv6
add asn to 159000 inetnums from registry arin, among them, 0 are ipv6
add asn to 160000 inetnums from registry arin, among them, 0 are ipv6
add asn to 161000 inetnums from registry arin, among them, 0 are ipv6
add asn to 162000 inetnums from registry arin, among them, 0 are ipv6
add asn to 163000 inetnums from registry arin, among them, 0 are ipv6
add asn to 164000 inetnums from registry arin, among them, 0 are ipv6
add asn to 165000 inetnums from registry arin, among them, 0 are ipv6
add asn to 166000 inetnums from registry arin, among them, 0 are ipv6
add asn to 167000 inetnums from registry arin, among them, 0 are ipv6
add asn to 168000 inetnums from registry arin, among them, 0 are ipv6
add asn to 169000 inetnums from registry arin, among them, 0 are ipv6
add asn to 170000 inetnums from registry arin, among them, 0 are ipv6
add asn to 171000 inetnums from registry arin, among them, 0 are ipv6
add asn to 172000 inetnums from registry arin, among them, 0 are ipv6
add asn to 173000 inetnums from registry arin, among them, 0 are ipv6
add asn to 174000 inetnums from registry arin, among them, 0 are ipv6
add asn to 175000 inetnums from registry arin, among them, 0 are ipv6
add asn to 176000 inetnums from registry arin, among them, 0 are ipv6
add asn to 177000 inetnums from registry arin, among them, 0 are ipv6
add asn to 178000 inetnums from registry arin, among them, 0 are ipv6
add asn to 179000 inetnums from registry arin, among them, 0 are ipv6
add asn to 180000 inetnums from registry arin, among them, 0 are ipv6
add asn to 181000 inetnums from registry arin, among them, 0 are ipv6
add asn to 182000 inetnums from registry arin, among them, 0 are ipv6
add asn to 183000 inetnums from registry arin, among them, 0 are ipv6
add asn to 184000 inetnums from registry arin, among them, 0 are ipv6
add asn to 185000 inetnums from registry arin, among them, 0 are ipv6
add asn to 186000 inetnums from registry arin, among them, 0 are ipv6
add asn to 187000 inetnums from registry arin, among them, 0 are ipv6
add asn to 188000 inetnums from registry arin, among them, 0 are ipv6
add asn to 189000 inetnums from registry arin, among them, 0 are ipv6
add asn to 190000 inetnums from registry arin, among them, 0 are ipv6
add asn to 191000 inetnums from registry arin, among them, 0 are ipv6
add asn to 192000 inetnums from registry arin, among them, 0 are ipv6
add asn to 193000 inetnums from registry arin, among them, 0 are ipv6
add asn to 194000 inetnums from registry arin, among them, 0 are ipv6
add asn to 195000 inetnums from registry arin, among them, 0 are ipv6
add asn to 196000 inetnums from registry arin, among them, 0 are ipv6
add asn to 197000 inetnums from registry arin, among them, 0 are ipv6
add asn to 198000 inetnums from registry arin, among them, 0 are ipv6
add asn to 199000 inetnums from registry arin, among them, 0 are ipv6
add asn to 200000 inetnums from registry arin, among them, 0 are ipv6
add asn to 201000 inetnums from registry arin, among them, 0 are ipv6
add asn to 202000 inetnums from registry arin, among them, 0 are ipv6
add asn to 203000 inetnums from registry arin, among them, 0 are ipv6
add asn to 204000 inetnums from registry arin, among them, 0 are ipv6
add asn to 205000 inetnums from registry arin, among them, 0 are ipv6
add asn to 206000 inetnums from registry arin, among them, 0 are ipv6
add asn to 207000 inetnums from registry arin, among them, 0 are ipv6
add asn to 208000 inetnums from registry arin, among them, 0 are ipv6
add asn to 209000 inetnums from registry arin, among them, 0 are ipv6
add asn to 210000 inetnums from registry arin, among them, 0 are ipv6
add asn to 211000 inetnums from registry arin, among them, 0 are ipv6
add asn to 212000 inetnums from registry arin, among them, 0 are ipv6
add asn to 213000 inetnums from registry arin, among them, 0 are ipv6
add asn to 214000 inetnums from registry arin, among them, 0 are ipv6
add asn to 215000 inetnums from registry arin, among them, 0 are ipv6
add asn to 216000 inetnums from registry arin, among them, 0 are ipv6
add asn to 217000 inetnums from registry arin, among them, 0 are ipv6
add asn to 218000 inetnums from registry arin, among them, 0 are ipv6
add asn to 219000 inetnums from registry arin, among them, 0 are ipv6
add asn to 220000 inetnums from registry arin, among them, 0 are ipv6
add asn to 221000 inetnums from registry arin, among them, 0 are ipv6
add asn to 222000 inetnums from registry arin, among them, 0 are ipv6
add asn to 223000 inetnums from registry arin, among them, 0 are ipv6
add asn to 224000 inetnums from registry arin, among them, 0 are ipv6
add asn to 225000 inetnums from registry arin, among them, 0 are ipv6
add asn to 226000 inetnums from registry arin, among them, 0 are ipv6
add asn to 227000 inetnums from registry arin, among them, 0 are ipv6
add asn to 228000 inetnums from registry arin, among them, 0 are ipv6
add asn to 229000 inetnums from registry arin, among them, 0 are ipv6
add asn to 230000 inetnums from registry arin, among them, 0 are ipv6
add asn to 231000 inetnums from registry arin, among them, 0 are ipv6
add asn to 232000 inetnums from registry arin, among them, 0 are ipv6
add asn to 233000 inetnums from registry arin, among them, 0 are ipv6
add asn to 234000 inetnums from registry arin, among them, 0 are ipv6
add asn to 235000 inetnums from registry arin, among them, 0 are ipv6
add asn to 236000 inetnums from registry arin, among them, 0 are ipv6
add asn to 237000 inetnums from registry arin, among them, 0 are ipv6
add asn to 238000 inetnums from registry arin, among them, 0 are ipv6
add asn to 239000 inetnums from registry arin, among them, 0 are ipv6
add asn to 240000 inetnums from registry arin, among them, 0 are ipv6
add asn to 241000 inetnums from registry arin, among them, 0 are ipv6
add asn to 242000 inetnums from registry arin, among them, 0 are ipv6
add asn to 243000 inetnums from registry arin, among them, 0 are ipv6
add asn to 244000 inetnums from registry arin, among them, 0 are ipv6
add asn to 245000 inetnums from registry arin, among them, 0 are ipv6
add asn to 246000 inetnums from registry arin, among them, 0 are ipv6
add asn to 247000 inetnums from registry arin, among them, 0 are ipv6
add asn to 248000 inetnums from registry arin, among them, 0 are ipv6
add asn to 249000 inetnums from registry arin, among them, 0 are ipv6
add asn to 250000 inetnums from registry arin, among them, 0 are ipv6
add asn to 251000 inetnums from registry arin, among them, 0 are ipv6
add asn to 252000 inetnums from registry arin, among them, 0 are ipv6
add asn to 253000 inetnums from registry arin, among them, 0 are ipv6
add asn to 254000 inetnums from registry arin, among them, 0 are ipv6
add asn to 255000 inetnums from registry arin, among them, 0 are ipv6
add asn to 256000 inetnums from registry arin, among them, 0 are ipv6
add asn to 257000 inetnums from registry arin, among them, 0 are ipv6
add asn to 258000 inetnums from registry arin, among them, 0 are ipv6
add asn to 259000 inetnums from registry arin, among them, 0 are ipv6
add asn to 260000 inetnums from registry arin, among them, 0 are ipv6
add asn to 261000 inetnums from registry arin, among them, 0 are ipv6
add asn to 262000 inetnums from registry arin, among them, 0 are ipv6
add asn to 263000 inetnums from registry arin, among them, 0 are ipv6
add asn to 264000 inetnums from registry arin, among them, 0 are ipv6
add asn to 265000 inetnums from registry arin, among them, 0 are ipv6
add asn to 266000 inetnums from registry arin, among them, 0 are ipv6
add asn to 267000 inetnums from registry arin, among them, 0 are ipv6
add asn to 268000 inetnums from registry arin, among them, 0 are ipv6
add asn to 269000 inetnums from registry arin, among them, 0 are ipv6
add asn to 270000 inetnums from registry arin, among them, 0 are ipv6
add asn to 271000 inetnums from registry arin, among them, 0 are ipv6
add asn to 272000 inetnums from registry arin, among them, 0 are ipv6
add asn to 273000 inetnums from registry arin, among them, 0 are ipv6
add asn to 274000 inetnums from registry arin, among them, 0 are ipv6
add asn to 275000 inetnums from registry arin, among them, 0 are ipv6
add asn to 276000 inetnums from registry arin, among them, 0 are ipv6
add asn to 277000 inetnums from registry arin, among them, 0 are ipv6
add asn to 278000 inetnums from registry arin, among them, 0 are ipv6
add asn to 279000 inetnums from registry arin, among them, 0 are ipv6
add asn to 280000 inetnums from registry arin, among them, 0 are ipv6
add asn to 281000 inetnums from registry arin, among them, 0 are ipv6
add asn to 282000 inetnums from registry arin, among them, 0 are ipv6
add asn to 283000 inetnums from registry arin, among them, 0 are ipv6
add asn to 284000 inetnums from registry arin, among them, 0 are ipv6
add asn to 285000 inetnums from registry arin, among them, 0 are ipv6
add asn to 286000 inetnums from registry arin, among them, 0 are ipv6
add asn to 287000 inetnums from registry arin, among them, 0 are ipv6
add asn to 288000 inetnums from registry arin, among them, 0 are ipv6
add asn to 289000 inetnums from registry arin, among them, 0 are ipv6
add asn to 290000 inetnums from registry arin, among them, 0 are ipv6
add asn to 291000 inetnums from registry arin, among them, 0 are ipv6
add asn to 292000 inetnums from registry arin, among them, 0 are ipv6
add asn to 293000 inetnums from registry arin, among them, 0 are ipv6
add asn to 294000 inetnums from registry arin, among them, 0 are ipv6
add asn to 295000 inetnums from registry arin, among them, 0 are ipv6
add asn to 296000 inetnums from registry arin, among them, 0 are ipv6
add asn to 297000 inetnums from registry arin, among them, 0 are ipv6
add asn to 298000 inetnums from registry arin, among them, 0 are ipv6
add asn to 299000 inetnums from registry arin, among them, 0 are ipv6
add asn to 300000 inetnums from registry arin, among them, 0 are ipv6
add asn to 301000 inetnums from registry arin, among them, 0 are ipv6
add asn to 302000 inetnums from registry arin, among them, 0 are ipv6
add asn to 303000 inetnums from registry arin, among them, 0 are ipv6
add asn to 304000 inetnums from registry arin, among them, 0 are ipv6
add asn to 305000 inetnums from registry arin, among them, 0 are ipv6
add asn to 306000 inetnums from registry arin, among them, 0 are ipv6
add asn to 307000 inetnums from registry arin, among them, 0 are ipv6
add asn to 308000 inetnums from registry arin, among them, 0 are ipv6
add asn to 309000 inetnums from registry arin, among them, 0 are ipv6
add asn to 310000 inetnums from registry arin, among them, 0 are ipv6
add asn to 311000 inetnums from registry arin, among them, 0 are ipv6
add asn to 312000 inetnums from registry arin, among them, 0 are ipv6
add asn to 313000 inetnums from registry arin, among them, 0 are ipv6
add asn to 314000 inetnums from registry arin, among them, 0 are ipv6
add asn to 315000 inetnums from registry arin, among them, 0 are ipv6
add asn to 316000 inetnums from registry arin, among them, 0 are ipv6
add asn to 317000 inetnums from registry arin, among them, 0 are ipv6
add asn to 318000 inetnums from registry arin, among them, 0 are ipv6
add asn to 319000 inetnums from registry arin, among them, 0 are ipv6
add asn to 320000 inetnums from registry arin, among them, 0 are ipv6
add asn to 321000 inetnums from registry arin, among them, 0 are ipv6
add asn to 322000 inetnums from registry arin, among them, 0 are ipv6
add asn to 323000 inetnums from registry arin, among them, 0 are ipv6
add asn to 324000 inetnums from registry arin, among them, 0 are ipv6
add asn to 325000 inetnums from registry arin, among them, 0 are ipv6
add asn to 326000 inetnums from registry arin, among them, 0 are ipv6
add asn to 327000 inetnums from registry arin, among them, 0 are ipv6
add asn to 328000 inetnums from registry arin, among them, 0 are ipv6
add asn to 329000 inetnums from registry arin, among them, 0 are ipv6
add asn to 330000 inetnums from registry arin, among them, 0 are ipv6
add asn to 331000 inetnums from registry arin, among them, 0 are ipv6
add asn to 332000 inetnums from registry arin, among them, 0 are ipv6
add asn to 333000 inetnums from registry arin, among them, 0 are ipv6
add asn to 334000 inetnums from registry arin, among them, 0 are ipv6
add asn to 335000 inetnums from registry arin, among them, 0 are ipv6
add asn to 336000 inetnums from registry arin, among them, 0 are ipv6
add asn to 337000 inetnums from registry arin, among them, 0 are ipv6
add asn to 338000 inetnums from registry arin, among them, 0 are ipv6
add asn to 339000 inetnums from registry arin, among them, 0 are ipv6
add asn to 340000 inetnums from registry arin, among them, 0 are ipv6
add asn to 341000 inetnums from registry arin, among them, 0 are ipv6
add asn to 342000 inetnums from registry arin, among them, 0 are ipv6
add asn to 343000 inetnums from registry arin, among them, 0 are ipv6
add asn to 344000 inetnums from registry arin, among them, 0 are ipv6
add asn to 345000 inetnums from registry arin, among them, 0 are ipv6
add asn to 346000 inetnums from registry arin, among them, 0 are ipv6
add asn to 347000 inetnums from registry arin, among them, 0 are ipv6
add asn to 348000 inetnums from registry arin, among them, 0 are ipv6
add asn to 349000 inetnums from registry arin, among them, 0 are ipv6
add asn to 350000 inetnums from registry arin, among them, 0 are ipv6
add asn to 351000 inetnums from registry arin, among them, 0 are ipv6
add asn to 352000 inetnums from registry arin, among them, 0 are ipv6
add asn to 353000 inetnums from registry arin, among them, 0 are ipv6
add asn to 354000 inetnums from registry arin, among them, 0 are ipv6
add asn to 355000 inetnums from registry arin, among them, 0 are ipv6
add asn to 356000 inetnums from registry arin, among them, 0 are ipv6
add asn to 357000 inetnums from registry arin, among them, 0 are ipv6
add asn to 358000 inetnums from registry arin, among them, 0 are ipv6
add asn to 359000 inetnums from registry arin, among them, 0 are ipv6
add asn to 360000 inetnums from registry arin, among them, 0 are ipv6
add asn to 361000 inetnums from registry arin, among them, 0 are ipv6
add asn to 362000 inetnums from registry arin, among them, 0 are ipv6
add asn to 363000 inetnums from registry arin, among them, 0 are ipv6
add asn to 364000 inetnums from registry arin, among them, 0 are ipv6
add asn to 365000 inetnums from registry arin, among them, 0 are ipv6
add asn to 366000 inetnums from registry arin, among them, 0 are ipv6
add asn to 367000 inetnums from registry arin, among them, 0 are ipv6
add asn to 368000 inetnums from registry arin, among them, 0 are ipv6
add asn to 369000 inetnums from registry arin, among them, 0 are ipv6
add asn to 370000 inetnums from registry arin, among them, 0 are ipv6
add asn to 371000 inetnums from registry arin, among them, 0 are ipv6
add asn to 372000 inetnums from registry arin, among them, 0 are ipv6
add asn to 373000 inetnums from registry arin, among them, 0 are ipv6
add asn to 374000 inetnums from registry arin, among them, 0 are ipv6
add asn to 375000 inetnums from registry arin, among them, 0 are ipv6
add asn to 376000 inetnums from registry arin, among them, 0 are ipv6
add asn to 377000 inetnums from registry arin, among them, 0 are ipv6
add asn to 378000 inetnums from registry arin, among them, 0 are ipv6
add asn to 379000 inetnums from registry arin, among them, 0 are ipv6
add asn to 380000 inetnums from registry arin, among them, 0 are ipv6
add asn to 381000 inetnums from registry arin, among them, 0 are ipv6
add asn to 382000 inetnums from registry arin, among them, 0 are ipv6
add asn to 383000 inetnums from registry arin, among them, 0 are ipv6
add asn to 384000 inetnums from registry arin, among them, 0 are ipv6
add asn to 385000 inetnums from registry arin, among them, 0 are ipv6
add asn to 386000 inetnums from registry arin, among them, 0 are ipv6
add asn to 387000 inetnums from registry arin, among them, 0 are ipv6
add asn to 388000 inetnums from registry arin, among them, 0 are ipv6
add asn to 389000 inetnums from registry arin, among them, 0 are ipv6
add asn to 390000 inetnums from registry arin, among them, 0 are ipv6
add asn to 391000 inetnums from registry arin, among them, 0 are ipv6
add asn to 392000 inetnums from registry arin, among them, 0 are ipv6
add asn to 393000 inetnums from registry arin, among them, 0 are ipv6
add asn to 394000 inetnums from registry arin, among them, 0 are ipv6
add asn to 395000 inetnums from registry arin, among them, 0 are ipv6
add asn to 396000 inetnums from registry arin, among them, 0 are ipv6
add asn to 397000 inetnums from registry arin, among them, 0 are ipv6
add asn to 398000 inetnums from registry arin, among them, 0 are ipv6
add asn to 399000 inetnums from registry arin, among them, 0 are ipv6
add asn to 400000 inetnums from registry arin, among them, 0 are ipv6
add asn to 401000 inetnums from registry arin, among them, 0 are ipv6
add asn to 402000 inetnums from registry arin, among them, 0 are ipv6
add asn to 403000 inetnums from registry arin, among them, 0 are ipv6
add asn to 404000 inetnums from registry arin, among them, 0 are ipv6
add asn to 405000 inetnums from registry arin, among them, 0 are ipv6
add asn to 406000 inetnums from registry arin, among them, 0 are ipv6
add asn to 407000 inetnums from registry arin, among them, 0 are ipv6
add asn to 408000 inetnums from registry arin, among them, 0 are ipv6
add asn to 409000 inetnums from registry arin, among them, 0 are ipv6
add asn to 410000 inetnums from registry arin, among them, 0 are ipv6
add asn to 411000 inetnums from registry arin, among them, 0 are ipv6
add asn to 412000 inetnums from registry arin, among them, 0 are ipv6
add asn to 413000 inetnums from registry arin, among them, 0 are ipv6
add asn to 414000 inetnums from registry arin, among them, 0 are ipv6
add asn to 415000 inetnums from registry arin, among them, 0 are ipv6
add asn to 416000 inetnums from registry arin, among them, 0 are ipv6
add asn to 417000 inetnums from registry arin, among them, 0 are ipv6
add asn to 418000 inetnums from registry arin, among them, 0 are ipv6
add asn to 419000 inetnums from registry arin, among them, 0 are ipv6
add asn to 420000 inetnums from registry arin, among them, 0 are ipv6
add asn to 421000 inetnums from registry arin, among them, 0 are ipv6
add asn to 422000 inetnums from registry arin, among them, 0 are ipv6
add asn to 423000 inetnums from registry arin, among them, 0 are ipv6
add asn to 424000 inetnums from registry arin, among them, 0 are ipv6
add asn to 425000 inetnums from registry arin, among them, 0 are ipv6
add asn to 426000 inetnums from registry arin, among them, 0 are ipv6
add asn to 427000 inetnums from registry arin, among them, 0 are ipv6
add asn to 428000 inetnums from registry arin, among them, 0 are ipv6
add asn to 429000 inetnums from registry arin, among them, 0 are ipv6
add asn to 430000 inetnums from registry arin, among them, 0 are ipv6
add asn to 431000 inetnums from registry arin, among them, 0 are ipv6
add asn to 432000 inetnums from registry arin, among them, 0 are ipv6
add asn to 433000 inetnums from registry arin, among them, 0 are ipv6
add asn to 434000 inetnums from registry arin, among them, 0 are ipv6
add asn to 435000 inetnums from registry arin, among them, 0 are ipv6
add asn to 436000 inetnums from registry arin, among them, 0 are ipv6
add asn to 437000 inetnums from registry arin, among them, 0 are ipv6
add asn to 438000 inetnums from registry arin, among them, 0 are ipv6
add asn to 439000 inetnums from registry arin, among them, 0 are ipv6
add asn to 440000 inetnums from registry arin, among them, 0 are ipv6
add asn to 441000 inetnums from registry arin, among them, 0 are ipv6
add asn to 442000 inetnums from registry arin, among them, 0 are ipv6
add asn to 443000 inetnums from registry arin, among them, 0 are ipv6
add asn to 444000 inetnums from registry arin, among them, 0 are ipv6
add asn to 445000 inetnums from registry arin, among them, 0 are ipv6
add asn to 446000 inetnums from registry arin, among them, 0 are ipv6
add asn to 447000 inetnums from registry arin, among them, 0 are ipv6
add asn to 448000 inetnums from registry arin, among them, 0 are ipv6
add asn to 449000 inetnums from registry arin, among them, 0 are ipv6
add asn to 450000 inetnums from registry arin, among them, 0 are ipv6
add asn to 451000 inetnums from registry arin, among them, 0 are ipv6
add asn to 452000 inetnums from registry arin, among them, 0 are ipv6
add asn to 453000 inetnums from registry arin, among them, 0 are ipv6
add asn to 454000 inetnums from registry arin, among them, 0 are ipv6
add asn to 455000 inetnums from registry arin, among them, 0 are ipv6
add asn to 456000 inetnums from registry arin, among them, 0 are ipv6
add asn to 457000 inetnums from registry arin, among them, 0 are ipv6
add asn to 458000 inetnums from registry arin, among them, 0 are ipv6
add asn to 459000 inetnums from registry arin, among them, 0 are ipv6
add asn to 460000 inetnums from registry arin, among them, 0 are ipv6
add asn to 461000 inetnums from registry arin, among them, 0 are ipv6
add asn to 462000 inetnums from registry arin, among them, 0 are ipv6
add asn to 463000 inetnums from registry arin, among them, 0 are ipv6
add asn to 464000 inetnums from registry arin, among them, 0 are ipv6
add asn to 465000 inetnums from registry arin, among them, 0 are ipv6
add asn to 466000 inetnums from registry arin, among them, 0 are ipv6
add asn to 467000 inetnums from registry arin, among them, 0 are ipv6
add asn to 468000 inetnums from registry arin, among them, 0 are ipv6
add asn to 469000 inetnums from registry arin, among them, 0 are ipv6
add asn to 470000 inetnums from registry arin, among them, 0 are ipv6
add asn to 471000 inetnums from registry arin, among them, 0 are ipv6
add asn to 472000 inetnums from registry arin, among them, 0 are ipv6
add asn to 473000 inetnums from registry arin, among them, 0 are ipv6
add asn to 474000 inetnums from registry arin, among them, 0 are ipv6
add asn to 475000 inetnums from registry arin, among them, 0 are ipv6
add asn to 476000 inetnums from registry arin, among them, 0 are ipv6
add asn to 477000 inetnums from registry arin, among them, 0 are ipv6
add asn to 478000 inetnums from registry arin, among them, 0 are ipv6
add asn to 479000 inetnums from registry arin, among them, 0 are ipv6
add asn to 480000 inetnums from registry arin, among them, 0 are ipv6
add asn to 481000 inetnums from registry arin, among them, 0 are ipv6
add asn to 482000 inetnums from registry arin, among them, 0 are ipv6
add asn to 483000 inetnums from registry arin, among them, 0 are ipv6
add asn to 484000 inetnums from registry arin, among them, 0 are ipv6
add asn to 485000 inetnums from registry arin, among them, 0 are ipv6
add asn to 486000 inetnums from registry arin, among them, 0 are ipv6
add asn to 487000 inetnums from registry arin, among them, 0 are ipv6
add asn to 488000 inetnums from registry arin, among them, 0 are ipv6
add asn to 489000 inetnums from registry arin, among them, 0 are ipv6
add asn to 490000 inetnums from registry arin, among them, 0 are ipv6
add asn to 491000 inetnums from registry arin, among them, 0 are ipv6
add asn to 492000 inetnums from registry arin, among them, 0 are ipv6
add asn to 493000 inetnums from registry arin, among them, 0 are ipv6
add asn to 494000 inetnums from registry arin, among them, 0 are ipv6
add asn to 495000 inetnums from registry arin, among them, 0 are ipv6
add asn to 496000 inetnums from registry arin, among them, 0 are ipv6
add asn to 497000 inetnums from registry arin, among them, 0 are ipv6
add asn to 498000 inetnums from registry arin, among them, 0 are ipv6
add asn to 499000 inetnums from registry arin, among them, 0 are ipv6
add asn to 500000 inetnums from registry arin, among them, 0 are ipv6
add asn to 501000 inetnums from registry arin, among them, 0 are ipv6
add asn to 502000 inetnums from registry arin, among them, 0 are ipv6
add asn to 503000 inetnums from registry arin, among them, 0 are ipv6
add asn to 504000 inetnums from registry arin, among them, 0 are ipv6
add asn to 505000 inetnums from registry arin, among them, 0 are ipv6
add asn to 506000 inetnums from registry arin, among them, 0 are ipv6
add asn to 507000 inetnums from registry arin, among them, 0 are ipv6
add asn to 508000 inetnums from registry arin, among them, 0 are ipv6
add asn to 509000 inetnums from registry arin, among them, 0 are ipv6
add asn to 510000 inetnums from registry arin, among them, 0 are ipv6
add asn to 511000 inetnums from registry arin, among them, 0 are ipv6
add asn to 512000 inetnums from registry arin, among them, 0 are ipv6
add asn to 513000 inetnums from registry arin, among them, 0 are ipv6
add asn to 514000 inetnums from registry arin, among them, 0 are ipv6
add asn to 515000 inetnums from registry arin, among them, 0 are ipv6
add asn to 516000 inetnums from registry arin, among them, 0 are ipv6
add asn to 517000 inetnums from registry arin, among them, 0 are ipv6
add asn to 518000 inetnums from registry arin, among them, 0 are ipv6
add asn to 519000 inetnums from registry arin, among them, 0 are ipv6
add asn to 520000 inetnums from registry arin, among them, 0 are ipv6
add asn to 521000 inetnums from registry arin, among them, 0 are ipv6
add asn to 522000 inetnums from registry arin, among them, 0 are ipv6
add asn to 523000 inetnums from registry arin, among them, 0 are ipv6
add asn to 524000 inetnums from registry arin, among them, 0 are ipv6
add asn to 525000 inetnums from registry arin, among them, 0 are ipv6
add asn to 526000 inetnums from registry arin, among them, 0 are ipv6
add asn t